### ISSUE TITLE
weird volume in ~tpiano

### ISSUE THREAD

**Issue by wooloogooloo** [narcode/codeklavier-supercollider#3]
The ~tpiano/~tpiano2/~tpiano3 sometimes lose their connection to the sampleramp. As if it gets replaced. Whilst the other sounding volumes are still connected to the ~sampleramp. Which variable gets disconnected is random but this happened twice today and I think it may actually have happened in the past

**Comment by narcode** [comment]
According to my testing it wasn't random on the tpianoN but actually a Supercollider leaking channel. The fx that was supposed to grab from channel 22 was leaking into 0-1. So you were hearing the cloned toy piano meant for fx - that's why the variable sampleramp wasnt affecting it, but samplerampfx did change it. The fix is using a different channel rather than the buggy-leaky one, so now that cloned signal is going to channel 8. This works here! let me know if it also works for you.
👸 see last commit https://github.com/narcode/codeklavier-supercollider/commit/dbeeefaa3653755c4101460cd034bec844c03088
